#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# linting markdown
@npx markdownlint-cli --ignore node_modules .

# lint dotnet files
dotnet build /warnaserror

# format dotnet files
dotnet format


