name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: npm

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "microsoft"

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarCloud scanners
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}

      - name: 'Run: Init, Lint, TestWithCoverage'
        run: |
          dotnet-sonarscanner begin /k:"${{ env.PROJECT_KEY }}" \
            /o:"${{ env.ORGANIZATION }}" \
            /d:sonar.host.url="${{ env.SONAR_HOST_URL }}" \
            /d:sonar.cs.opencover.reportsPaths=**/coverage.xml \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          ./build.sh Init Lint TestWithCoverage
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        env:
          PROJECT_KEY: phucnt1992_testcontainers-101
          ORGANIZATION: phucnt1992
          SONAR_HOST_URL: https://sonarcloud.io
          ASPNETCORE_ENVIRONMENT: CI

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: src/TestContainers101.Api.Tests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
